spring.application.name=office-supplies-management


spring.datasource.url=jdbc:mysql://localhost:3307/office_supplies_db
spring.datasource.username=root
spring.datasource.password=111111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true